version: '1.0'

services:
  db:
    image: mysql:latest
    container_name: demo
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: datlq
      MYSQL_PASSWORD: 123123
      MYSQL_DATABASE: test_db
    ports:
      - "3309:3306"
    volumes:
      - demo:/var/lib/mysql

volumes:
  demo:
