version: '1.0'

services:
  db:
    image: mysql:latest
    container_name: shopping_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: datlq
      MYSQL_PASSWORD: 123123
      MYSQL_DATABASE: test_db
    ports:
      - "3309:3306"
    volumes:
      - shopping_container:/var/lib/mysql

volumes:
  shopping_container:
